// ==UserScript==
// @name	LIGHTS Forum Theme Picker
// @description	Change up the way LIGHTS forum looks!
// @match http://board.iamlights.com/*
// ==/UserScript==
(function(d,g){function m(a){var b=new XMLHttpRequest;b.onreadystatechange=function(){4==b.readyState&&200==b.status&&a.a(b.responseText)};a.type=a.type||"GET";b.open(a.type,a.url,a.async);b.send()}function t(a){a&&a.parentNode.removeChild(a)}function n(a){if(a.stylesheet){var b=a.name,c=d.createElement("link");c.id="LFTP-Style";c.type="text/css";c.rel="stylesheet";c.href=l+"themes/"+b+"/LTP_"+b+p+".css";d.head.appendChild(c)}a.script&&(b=a.name,c=d.createElement("script"),c.id="LFTP-Script",c.type=
"text/javascript",c.src=l+"themes/"+b+"/LTP_"+b+p+".js",d.head.appendChild(c));h=a;k("selectedTheme",a)}function k(a,b){if(1<arguments.length)window.localStorage.setItem("themePicker-"+a,JSON.stringify(b));else{var c=window.localStorage.getItem("themePicker-"+a);return null===c?null:JSON.parse(c)}}function q(a){t(d.getElementById("LFTP-themeSelector"));var b=d.createElement("select");b.id="LFTP-themeSelector";for(var c in a)if(a.hasOwnProperty(c)){var e=d.createElement("option");e.text=c;h.name===
c&&(e.selected=!0);b.appendChild(e)}d.body.appendChild(b);b.addEventListener("change",function(){k("selectedTheme",f[this.options[this.selectedIndex].value]);window.location=window.location})}function r(a){return(a=d.cookie.split("LFTP-"+a+"=")[1])?a.split(";")[0]:null}function s(a,b,c){a="LFTP-"+a;var e="";c&&(e=new Date,e.setTime(e.getTime()+864E5*c),e="; expires="+e.toGMTString());d.cookie=a+"="+b+e+"; path=/"}var l="http://jeremysawesome.com/LIGHTSForum/",p=".min",h=k("selectedTheme")||!1;!1!==
h&&n(h);var f=k("availableThemes")||!1;!1!==f&&q(f);if(null===r("Checked")||!1===h||!1===f)m({url:l+"themes.php",a:function(a){a=JSON.parse(a||"null");"null"!==a&&(!1===h&&n(a.Themes[a.DefaultTheme]),f=a.Themes,q(f),k("availableThemes",f))}}),m({url:l+"/updatecheck.php",a:function(a){a=JSON.parse(a||"null");if("null"!==a&&1!=a.version){var b=d.createElement("div");d.body.insertBefore(b,d.body.firstChild);b.style.textAlign="center";b.style.background="#fff";b.style.padding="10px";b.style.margin="15px 10px";
b.style.position="fixed";b.style.width="97%";b.style.border="2px solid black";b.style.zIndex="900";b.className="rounded";b.innerHTML='<h2 style="font-size: 1.5em;">A new version of the LIGHTS Forum Theme Picker is available.</h2><p>Your Current Version: 1 New Version: '+a.version+'</p><p><a href="'+l+'LIGHTS_Forum_theme_picker.php">Download it here.</a></p>'}}}),s("Checked",1,1);g.LFTP=g.LFTP||{};g.LFTP.filterElements=function(a,b,c,e){var d=[];e=e||1;for(var g=0;g<a.length;g++){var f=a[g];f.nodeType===
e&&f.tagName===b&&("undefined"!==typeof c&&c.apply(f),d.push(f))}return d};g.LFTP.ajax=m;g.LFTP.store=k;g.LFTP.getCookie=r;g.LFTP.setCookie=s})(document,unsafeWindow);